### ISSUE TITLE
Review #1 - Muy buena page!

### ISSUE THREAD

**Issue by FacundoEG** [pmpeloc/apx-desafio-m3#1]
Hola @pmpeloc como estas? primero que todo te felicito por haber terminado el desafío del modulo 3!

Te quería comentar que estuve revisando la page y funciona perfecto! la verdad que responde muy bien y se adapta a muchos px de ancho, destaco que hasta usándolo en resoluciones muy bajas se mantienen solidos los elementos.

La verdad que es un rotundo LGTM para mi, así que de mi parte de te deseo éxitos en el próximo modulo!

Te mando un saludo !

**Comment by pmpeloc** [comment]
Muchas gracias @FacundoEG por la devolución!

Abrazos!
